paths:
  .github/workflows/js-ts-npm-package-slsa3.yml:
    ignore:
      - 'property "workflow_repository" is not defined in object type'
      - 'property "workflow_sha" is not defined in object type'
